import React, { FC, useState } from 'react';
import User, { Challenges } from '@eximchain/dappbot-types/spec/user';
import { Button } from '../ui';
import { StringField } from '../fields';

interface MfaChallengeProps {
  user: User.AuthData
  setUser: (user:User.AuthData)=>void
  setErr: (err:string)=>void
  setChallenge: (challenge:Challenges.Data)=>void
}

export const MfaChallenge:FC<MfaChallengeProps> = ({user, setUser, setErr, setChallenge})=>{

  const [mfa, setMfa] = useState('');
  const [loading, setLoading] = useState(false);
  const sendMfa = async () => {
    setErr('');
    setLoading(true);
    try {
      //TODO: implement the new version of MFA api
      // setChallenge('');
    } catch (e) {
      setErr(e.toString())
    }
    setLoading(false);
  }

  return (
    <>
      <StringField name='mfa' 
        value={mfa}  
        displayName="Two-factor Auth Code"
        help="This code is generated by an app like Duo or Google Authenticator."
        onChange={setMfa} />
      <Button disabled={loading} block onClick={sendMfa}>Submit</Button>
    </>
  )
}

export default MfaChallenge;