import React, { FC, useState } from 'react';
import { Button } from '../components/ui';
import { StringField } from '../components/fields';
import Auth from '../services/auth';
import { CognitoUser } from '@aws-amplify/auth';

interface MfaChallengeProps {
  user: CognitoUser
  setUser: (user:any)=>void
  setErr: (err:string)=>void
  setChallenge: (challenge:string)=>void
}

export const MfaChallenge:FC<MfaChallengeProps> = ({user, setUser, setErr, setChallenge})=>{

  const [mfa, setMfa] = useState('');
  const [loading, setLoading] = useState(false);
  const sendMfa = async () => {
    setErr('');
    setLoading(true);
    try {
      const fullUser = await Auth.confirmMFA(user, mfa)
      setUser(fullUser);
      setChallenge('');
    } catch (e) {
      setErr(e.toString())
    }
    setLoading(false);
  }

  return (
    <>
      <StringField name='mfa' 
        value={mfa}  
        displayName="Two-factor Auth Code"
        help="This code is generated by an app like Duo or Google Authenticator."
        onChange={setMfa} />
      <Button disabled={loading} block onClick={sendMfa}>Submit</Button>
    </>
  )
}

export default MfaChallenge;